
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T12:30:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d03928c5dce70cf1540782c58f09d29c735fd014",
 "version": "5.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
