CONFIG_FILE_NAME = "config.ini"

APP_CONFIG_SECTION = "APP_CONFIG"
APP_CONFIG_STATIC = "APP_CONFIG_STATIC"
APP_CONFIG_DYNAMIC = "APP_CONFIG_DYNAMIC"

APP_NAME_KEY = "appName"
DEFAULT_APP_NAME = "defaultApp"
DYNAMIC_CONFIG_TTL_KEY = "dynamicConfigRefreshInterval"
DEFAULT_DYNAMIC_CONFIG_TTL = 10 #sec

LOG_LEVEL_KEY = "logLevel"
DEFAULT_LOG_LEVEL = "INFO"

FEATURES_CONFIG = "FEATURES"
FEATURES_TENANT_PREFIX = "t_"
FEATURES_CALLER_PREFIX = "c_"
FEATURES_CONFIG_TTL_KEY = "featureConfigRefreshInterval"
DEFAULT_FEATURES_CONFIG_TTL = 300 #sec

#Thread local items
THREADLOCAL_CALLER = "caller"
THREADLOCAL_TENANTID = "tenantId"
THREADLOCAL_CORRELATION_ID = "correlationId"

#HTTP Headers
HTTP_CORRELATION_ID_HEADER = "x-correlation-id"
HTTP_TENANT_ID_HEADER = "x-tenant-id"
HTTP_AUTH_HEADER = "Authorization" # This is to be used
HTTP_AUTH_KEY_HEADER = "x-auth-key" # This is to be used