
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-02T16:22:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dda04c3babf17e3b1983a808238f9d2ad7969efb",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
