
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-05T15:29:43+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "56b28b3e4149b0a9ab6f5322401b1c3f1fc95c1a",
 "version": "0.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
