# -*- coding: utf-8 -*-
# this file is generated by australians_calendar.scripts.generate_constants
from __future__ import absolute_import, unicode_literals

import datetime
from enum import Enum


class Holiday(Enum):
    def __new__(cls, english, chinese, days=0):
        obj = object.__new__(cls)
        obj._value_ = english

        obj.chinese = chinese
        obj.days = days
        return obj

    new_years_day = "New Year's Day", "元旦", 1
    australia_day = "Australia Day","澳大利亚国庆日",1
    good_friday = "Good Friday","耶稣受难日",1
    easter_saturday = "Easter Saturday","耶稣受难日翌日",1
    easter_sunday = "Easter Sunday","复活节星期日",1
    easter_monday = "Easter Monday","复活节星期一",1
    anzac_day = "Anzac Day","澳新军团日",1
    kings_birthday = "King's Birthday","国王诞辰日",1
    labour_day = "Labour Day","劳动节",1
    christmas_day = "Christmas Day","圣诞节",1
    boxing_day = "Boxing Day","节礼日",1


holidays = {
    datetime.date(year=2023, month=1, day=1): Holiday.new_years_day.value,
    datetime.date(year=2023, month=1, day=2): Holiday.new_years_day.value,
    datetime.date(year=2023, month=1, day=26): Holiday.australia_day.value,
    datetime.date(year=2023, month=4, day=7): Holiday.good_friday.value,
    datetime.date(year=2023, month=4, day=8): Holiday.easter_saturday.value,
    datetime.date(year=2023, month=4, day=9): Holiday.easter_sunday.value,
    datetime.date(year=2023, month=4, day=10): Holiday.easter_monday.value,
    datetime.date(year=2023, month=4, day=25): Holiday.anzac_day.value,
    datetime.date(year=2023, month=6, day=12): Holiday.kings_birthday.value,
    datetime.date(year=2023, month=10, day=2): Holiday.labour_day.value,
    datetime.date(year=2023, month=12, day=25): Holiday.christmas_day.value,
    datetime.date(year=2023, month=12, day=26): Holiday.boxing_day.value,


    datetime.date(year=2024, month=1, day=1): Holiday.new_years_day.value,
    datetime.date(year=2024, month=1, day=26): Holiday.australia_day.value,
    datetime.date(year=2024, month=3, day=29): Holiday.good_friday.value,
    datetime.date(year=2024, month=3, day=30): Holiday.easter_saturday.value,
    datetime.date(year=2024, month=3, day=31): Holiday.easter_sunday.value,
    datetime.date(year=2024, month=4, day=1): Holiday.easter_monday.value,
    datetime.date(year=2024, month=4, day=25): Holiday.anzac_day.value,
    datetime.date(year=2024, month=6, day=10): Holiday.kings_birthday.value,
    datetime.date(year=2024, month=10, day=7): Holiday.labour_day.value,
    datetime.date(year=2024, month=12, day=25): Holiday.christmas_day.value,
    datetime.date(year=2024, month=12, day=26): Holiday.boxing_day.value,
}

workdays = {

}

in_lieu_days = {}

