
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-03T16:17:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "567336e18ca2cf8aedb0ad2efc5b7b57fb985d21",
 "version": "2.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
