# Generated by Django 3.2.18 on 2023-06-15 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hashtag", "0002_alter_mytag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mytag",
            name="last_used",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
