
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-05T16:28:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8185fd8bae74e4c2e235df8ba67d4484ef8fd751",
 "version": "5.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
