# Generated by Django 5.0 on 2023-12-05 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Timespan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bookdates.calendar')),
            ],
        ),
    ]
