# Generated by Django 5.0 on 2023-12-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bookdates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timespan',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
