# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chains.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chain_pb2 as chain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63hains.proto\x1a\x0b\x63hain.proto\"d\n\x06\x43hains\x12#\n\x06\x63hains\x18\x01 \x03(\x0b\x32\x13.Chains.ChainsEntry\x1a\x35\n\x0b\x43hainsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Chain:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chains_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHAINS_CHAINSENTRY._options = None
  _CHAINS_CHAINSENTRY._serialized_options = b'8\001'
  _CHAINS._serialized_start=29
  _CHAINS._serialized_end=129
  _CHAINS_CHAINSENTRY._serialized_start=76
  _CHAINS_CHAINSENTRY._serialized_end=129
# @@protoc_insertion_point(module_scope)
