"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class JsonDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    URL_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    JSON_DATA_FIELD_NUMBER: builtins.int
    CAPTURE_KEY_FIELD_NUMBER: builtins.int
    WAIT_FOR_RESPONSE_FIELD_FIELD_NUMBER: builtins.int
    WAIT_FOR_RESPONSE_VALUE_FIELD_NUMBER: builtins.int
    url: builtins.str
    method: builtins.str
    @property
    def json_data(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    capture_key: builtins.str
    wait_for_response_field: builtins.str
    wait_for_response_value: builtins.str
    def __init__(
        self,
        *,
        url: builtins.str = ...,
        method: builtins.str = ...,
        json_data: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        capture_key: builtins.str = ...,
        wait_for_response_field: builtins.str = ...,
        wait_for_response_value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["capture_key", b"capture_key", "json_data", b"json_data", "method", b"method", "url", b"url", "wait_for_response_field", b"wait_for_response_field", "wait_for_response_value", b"wait_for_response_value"]) -> None: ...

global___Request = Request
