#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['conscript']

package_data = \
{'': ['*']}

extras_require = \
{":python_version <= '3.5'": ['setuptools'],
 ":python_version == '3.6' or python_version == '3.7'": ['importlib-metadata']}

entry_points = \
{'console_scripts': ['conscript = conscript.main:main']}

setup(name='conscript',
      version='0.1.7',
      description='Conscript console scripts in your own Swiss Army Knife.',
      author='John Sirois',
      author_email='john.sirois@gmail.com',
      url='https://github.com/jsirois/conscript',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=2.7,<3.14,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*',
     )
