
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-03T11:39:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6cc21a7ccb36b5bc61be88013185113b33841f1",
 "version": "2.27.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
