
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-07T02:16:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "54374e01eaa7a279d52b299e73016ba875045eb6",
 "version": "1.4.dev2401"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
