ENV_DEV = "dev"
ENV_STAGING = "staging"
ENV_PROD = "prod"
ENV_US = "us"

TYPE_BOT = "bot"
TYPE_USER = "user"
TYPE_SYSTEM = "system"

API_BAIDU = "baidu"
API_CLAUDE = "claude"
API_GOOGLE = "google"
API_MINIMAX = "minimax"
API_OPENAI = "openai"
API_XUNFEI = "xunfei"
API_DASHBOARD = "dashboard"
RECORD_APIS = [API_BAIDU, API_CLAUDE, API_GOOGLE, API_MINIMAX, API_OPENAI, API_XUNFEI]

ADMIN_APIS = [API_DASHBOARD]
ADMIN_USER_IDS = ["1"]

DATE_PATTERN = "%Y%m%d"
TIMEOUT_SECONDS = 30
DEFAULT_RPM = 30

TOKEN_FOR_OPENAI_CHECK = "$#@!THIS-TOKEN-FOR-OPENAI-CHECK-ONLY$#@!"
USER_ID_FOR_OPENAI_CHECK = "-99"

OPENAI_KEY_GPT35 = "key_gpt35"
OPENAI_KEY_GPT4 = "key_gpt40"

REDIS_KEY_POOLS_CONFIG = "alles-apin::pools"

VENDOR_OPENAI = "openai"
VENDOR_MINIMAX = API_MINIMAX
VENDOR_BAIDU = API_BAIDU
VENDOR_GOOGLE = API_GOOGLE
VENDOR_XUNFEI = API_XUNFEI
VENDOR_CLAUDE = API_CLAUDE
VENDOR_INTERNLM = "internlm"

RPM_USER_QUOTA_EXCEED = -99

RATE_LIMIT_NONE = 0
RATE_LIMIT_QUOTA_EXCEED = 1
RATE_LIMIT_RPM_EXCEED = 2

DEFAULT_TIMEOUT_SECONDS = 600
OPENAI_KEY_SIGN = "key-sign"
OPENAI_KEY_SIGN_PREFIX_GPT3 = "g3-"
OPENAI_KEY_SIGN_PREFIX_GPT4 = "g4-"

OPENAI_PROXY_ACCESS_UIDS = ["46", "53", "79"]

OPENAI_KEY_ERROR_RPM = "rpm"
OPENAI_KEY_ERROR_TPM = "tpm"
OPENAI_KEY_ERROR_RPD = "rpd"
OPENAI_KEY_ERROR_TPD = "tpd"
OPENAI_KEY_ERROR_QUOTA = "quota"
OPENAI_KEY_ERROR_INVALID = "invalid"
OPENAI_KEY_ERROR_UNKNOWN = "unknown"

OPENAI_ERROR_STR_RPM = ""
