__built_time__        =  "built at Thu Jan  4 01:04:13 2024_CST"
__name__              =  "pyasd"
__version__           =  "0.0.22"
__author__            =  "Shunhong Zhang"
__author_email__      =  "zhangshunhong.pku@gmail.com"
__url__               =  "https://to_be_posted"
__license__           =  "MIT LICENSE"
__platform__          =  "linux"
