#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Cryptomamy_kraken_api documentation build configuration file, created by
# sphinx-quickstart on Sat Apr 16 20:02:25 2016.

import sys
import os

# Ensure the directory containing your package is in sys.path
sys.path.insert(0, os.path.abspath('../../'))

# Import your package's version
from Cryptomamy_kraken_api.version import __version__ as version

# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- General configuration ------------------------------------------------

# General project information
project = 'Cryptomamy_kraken_api'
copyright = '2013-2023, [Your Name or Your Organization]'
author = 'Cryptomamy'

# The version info for the project, acts as replacement for |version| and |release|
release = version

# Add any Sphinx extension module names here, as strings.
# These are extensions coming with Sphinx or custom ones.
extensions = [
    'sphinx.ext.autodoc',  # Automatically document your code
    'sphinx.ext.intersphinx',  # Link to other project's documentation
    'sphinx.ext.coverage',  # Checks documentation coverage
    'sphinx.ext.ifconfig',  # Conditional documentation
    'sphinx.ext.viewcode',  # Add links to source code
    'sphinx.ext.githubpages',  # Publish HTML on GitHub pages
]

# The suffix(es) of source filenames.
source_suffix = '.rst'  # reStructuredText is the default source file format

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = None

# HTML theme to use for HTML pages
html_theme = 'sphinx_rtd_theme'  # Using the Read The Docs theme

# Output file base name for HTML help builder.
htmlhelp_basename = 'Cryptomamy_kraken_api_doc'

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),  # Link to Python docs
    'requests': ('http://docs.python-requests.org/en/master/', None),  # Link to requests library docs
}
