
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-01T18:30:15+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "fbdc565631611ffe7b482e98bbed07ecb2ecd9fb",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
