
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-02T18:28:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e20ad247121c3c306c20874ff0edb400e7cd91fa",
 "version": "2.27.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
