
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-06T13:09:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1a902191adf8e4e630b6bb07b0ba174f3aa38cf",
 "version": "1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
