
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-06T09:56:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "feef60d341cb1ae983cbd340038367d6caa6f4e9",
 "version": "3.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
