-- File: array8sorter_127.vhd
-- Generated by MyHDL 0.11.42
-- Date: Sun Jun 18 18:40:29 2023


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_01142.all;

entity array8sorter_127 is
    port (
        a_0: in unsigned(3 downto 0);
        a_1: in unsigned(3 downto 0);
        a_2: in unsigned(3 downto 0);
        a_3: in unsigned(3 downto 0);
        a_4: in unsigned(3 downto 0);
        a_5: in unsigned(3 downto 0);
        a_6: in unsigned(3 downto 0);
        a_7: in unsigned(3 downto 0);
        z_0: out unsigned(3 downto 0);
        z_1: out unsigned(3 downto 0);
        z_2: out unsigned(3 downto 0);
        z_3: out unsigned(3 downto 0);
        z_4: out unsigned(3 downto 0);
        z_5: out unsigned(3 downto 0);
        z_6: out unsigned(3 downto 0);
        z_7: out unsigned(3 downto 0)
    );
end entity array8sorter_127;
-- Sort Array with 8 values 

architecture MyHDL of array8sorter_127 is



signal bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort3_feedthru0_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort4_feedthru1_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge1_feedthru2_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge2_feedthru3_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort6_feedthru4_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort7_feedthru5_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge4_feedthru6_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge5_feedthru7_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge8_feedthru8_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge9_feedthru9_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge11_feedthru10_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge12_feedthru11_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort10_feedthru12_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort11_feedthru13_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge14_feedthru14_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge15_feedthru15_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort13_feedthru16_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort14_feedthru17_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge17_feedthru18_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge18_feedthru19_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge21_feedthru20_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge22_feedthru21_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge24_feedthru22_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge25_feedthru23_out_z: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare12_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare12_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare13_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare13_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare14_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare14_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare15_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_compare15_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_2: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_1: unsigned(3 downto 0);
signal bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_2: unsigned(3 downto 0);

begin




-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort3_feedthru0_out_z <= a_0;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort4_feedthru1_out_z <= a_1;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_SORT2_BITONIC_MERGE0_COMPARE0_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort3_feedthru0_out_z, bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort4_feedthru1_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort3_feedthru0_out_z > bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort4_feedthru1_out_z)) then
        bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort4_feedthru1_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort3_feedthru0_out_z;
    else
        bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort3_feedthru0_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_sort4_feedthru1_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_SORT2_BITONIC_MERGE0_COMPARE0_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge1_feedthru2_out_z <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge2_feedthru3_out_z <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_compare0_z_2;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort6_feedthru4_out_z <= a_2;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort7_feedthru5_out_z <= a_3;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_SORT5_BITONIC_MERGE3_COMPARE1_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort6_feedthru4_out_z, bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort7_feedthru5_out_z) is
begin
    if ('0' = stdl(bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort6_feedthru4_out_z > bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort7_feedthru5_out_z)) then
        bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort7_feedthru5_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort6_feedthru4_out_z;
    else
        bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort6_feedthru4_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_sort7_feedthru5_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_SORT5_BITONIC_MERGE3_COMPARE1_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge4_feedthru6_out_z <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge5_feedthru7_out_z <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_compare1_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_COMPARE2_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge1_feedthru2_out_z, bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge4_feedthru6_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge1_feedthru2_out_z > bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge4_feedthru6_out_z)) then
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge4_feedthru6_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge1_feedthru2_out_z;
    else
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge1_feedthru2_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge4_feedthru6_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_COMPARE2_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_COMPARE3_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge2_feedthru3_out_z, bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge5_feedthru7_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge2_feedthru3_out_z > bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge5_feedthru7_out_z)) then
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge5_feedthru7_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge2_feedthru3_out_z;
    else
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_sort2_bitonic_merge0_bitonic_merge2_feedthru3_out_z;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_sort5_bitonic_merge3_bitonic_merge5_feedthru7_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_COMPARE3_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_BITONIC_MERGE7_COMPARE4_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_1, bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_1) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_1 > bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_1)) then
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_1;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_1;
    else
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_1;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_1;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_BITONIC_MERGE7_COMPARE4_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge8_feedthru8_out_z <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge9_feedthru9_out_z <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_compare4_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_BITONIC_MERGE10_COMPARE5_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_2, bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_2) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_2 > bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_2)) then
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_2;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_2;
    else
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare2_z_2;
        bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_compare3_z_2;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT1_BITONIC_MERGE6_BITONIC_MERGE10_COMPARE5_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge11_feedthru10_out_z <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge12_feedthru11_out_z <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_compare5_z_2;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort10_feedthru12_out_z <= a_4;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort11_feedthru13_out_z <= a_5;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_SORT9_BITONIC_MERGE13_COMPARE6_LOGIC: process (bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort10_feedthru12_out_z, bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort11_feedthru13_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort10_feedthru12_out_z > bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort11_feedthru13_out_z)) then
        bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort11_feedthru13_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort10_feedthru12_out_z;
    else
        bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort10_feedthru12_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_sort11_feedthru13_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_SORT9_BITONIC_MERGE13_COMPARE6_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge14_feedthru14_out_z <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge15_feedthru15_out_z <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_compare6_z_2;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort13_feedthru16_out_z <= a_6;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort14_feedthru17_out_z <= a_7;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_SORT12_BITONIC_MERGE16_COMPARE7_LOGIC: process (bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort13_feedthru16_out_z, bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort14_feedthru17_out_z) is
begin
    if ('0' = stdl(bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort13_feedthru16_out_z > bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort14_feedthru17_out_z)) then
        bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort14_feedthru17_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort13_feedthru16_out_z;
    else
        bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort13_feedthru16_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_sort14_feedthru17_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_SORT12_BITONIC_MERGE16_COMPARE7_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge17_feedthru18_out_z <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge18_feedthru19_out_z <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_compare7_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_COMPARE8_LOGIC: process (bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge14_feedthru14_out_z, bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge17_feedthru18_out_z) is
begin
    if ('0' = stdl(bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge14_feedthru14_out_z > bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge17_feedthru18_out_z)) then
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge17_feedthru18_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge14_feedthru14_out_z;
    else
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge14_feedthru14_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge17_feedthru18_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_COMPARE8_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_COMPARE9_LOGIC: process (bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge15_feedthru15_out_z, bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge18_feedthru19_out_z) is
begin
    if ('0' = stdl(bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge15_feedthru15_out_z > bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge18_feedthru19_out_z)) then
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge18_feedthru19_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge15_feedthru15_out_z;
    else
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_sort9_bitonic_merge13_bitonic_merge15_feedthru15_out_z;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_sort12_bitonic_merge16_bitonic_merge18_feedthru19_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_COMPARE9_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_BITONIC_MERGE20_COMPARE10_LOGIC: process (bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_1, bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_1) is
begin
    if ('0' = stdl(bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_1 > bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_1)) then
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_1;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_1;
    else
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_1;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_1;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_BITONIC_MERGE20_COMPARE10_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge21_feedthru20_out_z <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge22_feedthru21_out_z <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_compare10_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_BITONIC_MERGE23_COMPARE11_LOGIC: process (bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_2, bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_2) is
begin
    if ('0' = stdl(bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_2 > bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_2)) then
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_2;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_2;
    else
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare8_z_2;
        bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_compare9_z_2;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_SORT8_BITONIC_MERGE19_BITONIC_MERGE23_COMPARE11_LOGIC;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge24_feedthru22_out_z <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_1;

-- Combinatorial logic 

bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge25_feedthru23_out_z <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_compare11_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE12_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge8_feedthru8_out_z, bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge21_feedthru20_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge8_feedthru8_out_z > bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge21_feedthru20_out_z)) then
        bitonic_sort0_bitonic_merge26_compare12_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge21_feedthru20_out_z;
        bitonic_sort0_bitonic_merge26_compare12_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge8_feedthru8_out_z;
    else
        bitonic_sort0_bitonic_merge26_compare12_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge8_feedthru8_out_z;
        bitonic_sort0_bitonic_merge26_compare12_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge21_feedthru20_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE12_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE13_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge9_feedthru9_out_z, bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge22_feedthru21_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge9_feedthru9_out_z > bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge22_feedthru21_out_z)) then
        bitonic_sort0_bitonic_merge26_compare13_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge22_feedthru21_out_z;
        bitonic_sort0_bitonic_merge26_compare13_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge9_feedthru9_out_z;
    else
        bitonic_sort0_bitonic_merge26_compare13_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge7_bitonic_merge9_feedthru9_out_z;
        bitonic_sort0_bitonic_merge26_compare13_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge20_bitonic_merge22_feedthru21_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE13_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE14_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge11_feedthru10_out_z, bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge24_feedthru22_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge11_feedthru10_out_z > bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge24_feedthru22_out_z)) then
        bitonic_sort0_bitonic_merge26_compare14_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge24_feedthru22_out_z;
        bitonic_sort0_bitonic_merge26_compare14_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge11_feedthru10_out_z;
    else
        bitonic_sort0_bitonic_merge26_compare14_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge11_feedthru10_out_z;
        bitonic_sort0_bitonic_merge26_compare14_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge24_feedthru22_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE14_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE15_LOGIC: process (bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge12_feedthru11_out_z, bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge25_feedthru23_out_z) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge12_feedthru11_out_z > bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge25_feedthru23_out_z)) then
        bitonic_sort0_bitonic_merge26_compare15_z_1 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge25_feedthru23_out_z;
        bitonic_sort0_bitonic_merge26_compare15_z_2 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge12_feedthru11_out_z;
    else
        bitonic_sort0_bitonic_merge26_compare15_z_1 <= bitonic_sort0_bitonic_sort1_bitonic_merge6_bitonic_merge10_bitonic_merge12_feedthru11_out_z;
        bitonic_sort0_bitonic_merge26_compare15_z_2 <= bitonic_sort0_bitonic_sort8_bitonic_merge19_bitonic_merge23_bitonic_merge25_feedthru23_out_z;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_COMPARE15_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_COMPARE16_LOGIC: process (bitonic_sort0_bitonic_merge26_compare12_z_1, bitonic_sort0_bitonic_merge26_compare14_z_1) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_compare12_z_1 > bitonic_sort0_bitonic_merge26_compare14_z_1)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_1 <= bitonic_sort0_bitonic_merge26_compare14_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_2 <= bitonic_sort0_bitonic_merge26_compare12_z_1;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_1 <= bitonic_sort0_bitonic_merge26_compare12_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_2 <= bitonic_sort0_bitonic_merge26_compare14_z_1;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_COMPARE16_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_COMPARE17_LOGIC: process (bitonic_sort0_bitonic_merge26_compare13_z_1, bitonic_sort0_bitonic_merge26_compare15_z_1) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_compare13_z_1 > bitonic_sort0_bitonic_merge26_compare15_z_1)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_1 <= bitonic_sort0_bitonic_merge26_compare15_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_2 <= bitonic_sort0_bitonic_merge26_compare13_z_1;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_1 <= bitonic_sort0_bitonic_merge26_compare13_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_2 <= bitonic_sort0_bitonic_merge26_compare15_z_1;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_COMPARE17_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_BITONIC_MERGE28_COMPARE18_LOGIC: process (bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_1, bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_1) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_1 > bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_1)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_1;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_1;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_BITONIC_MERGE28_COMPARE18_LOGIC;

-- Combinatorial logic 

z_0 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_1;

-- Combinatorial logic 

z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge28_compare18_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_BITONIC_MERGE31_COMPARE19_LOGIC: process (bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_2, bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_2) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_2 > bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_2)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_2;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare16_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_compare17_z_2;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE27_BITONIC_MERGE31_COMPARE19_LOGIC;

-- Combinatorial logic 

z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_1;

-- Combinatorial logic 

z_3 <= bitonic_sort0_bitonic_merge26_bitonic_merge27_bitonic_merge31_compare19_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_COMPARE20_LOGIC: process (bitonic_sort0_bitonic_merge26_compare12_z_2, bitonic_sort0_bitonic_merge26_compare14_z_2) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_compare12_z_2 > bitonic_sort0_bitonic_merge26_compare14_z_2)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_1 <= bitonic_sort0_bitonic_merge26_compare14_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_2 <= bitonic_sort0_bitonic_merge26_compare12_z_2;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_1 <= bitonic_sort0_bitonic_merge26_compare12_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_2 <= bitonic_sort0_bitonic_merge26_compare14_z_2;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_COMPARE20_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_COMPARE21_LOGIC: process (bitonic_sort0_bitonic_merge26_compare13_z_2, bitonic_sort0_bitonic_merge26_compare15_z_2) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_compare13_z_2 > bitonic_sort0_bitonic_merge26_compare15_z_2)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_1 <= bitonic_sort0_bitonic_merge26_compare15_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_2 <= bitonic_sort0_bitonic_merge26_compare13_z_2;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_1 <= bitonic_sort0_bitonic_merge26_compare13_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_2 <= bitonic_sort0_bitonic_merge26_compare15_z_2;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_COMPARE21_LOGIC;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_BITONIC_MERGE35_COMPARE22_LOGIC: process (bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_1, bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_1) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_1 > bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_1)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_1;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_1;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_1;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_BITONIC_MERGE35_COMPARE22_LOGIC;

-- Combinatorial logic 

z_4 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_1;

-- Combinatorial logic 

z_5 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge35_compare22_z_2;

-- Combinatorial logic 
ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_BITONIC_MERGE38_COMPARE23_LOGIC: process (bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_2, bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_2) is
begin
    if ('1' = stdl(bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_2 > bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_2)) then
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_2;
    else
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_1 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare20_z_2;
        bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_2 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_compare21_z_2;
    end if;
end process ARRAY8SORTER_127_BITONIC_SORT0_BITONIC_MERGE26_BITONIC_MERGE34_BITONIC_MERGE38_COMPARE23_LOGIC;

-- Combinatorial logic 

z_6 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_1;

-- Combinatorial logic 

z_7 <= bitonic_sort0_bitonic_merge26_bitonic_merge34_bitonic_merge38_compare23_z_2;

end architecture MyHDL;
