-- File: bug_28.vhd
-- Generated by MyHDL 0.11.42
-- Date: Sun Jun 18 18:40:40 2023


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_01142.all;

entity bug_28 is
    port (
        dout: out unsigned(15 downto 0);
        channel: in unsigned(3 downto 0)
    );
end entity bug_28;


architecture MyHDL of bug_28 is




begin





dout <= (32816 + shift_left(resize(channel, 16), 10));

end architecture MyHDL;
