
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T10:50:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf76477b4087feefc8ad429ebd492e30ef10eebc",
 "version": "0.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
