# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/couchbase_version.py
# at
#    2023-12-22 00:31:46.532205
__version__ = '4.1.10rc1'