
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-04T09:44:57+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "05396c2f70823d6278709405049e37c567de6e1a",
 "version": "0.6.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
