
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T11:56:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "69d1aef0f5a322d3186d53d8b0155813fb502d24",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
