# Version file autogenerated by the build process
version = '0.13.9'
build = 1315
vcs_info = 'Git SHA1 818f9187 committed on 2024-01-04'
package_name = 'ksconf'

SHELL_VER_VARS = 'KSCONF_VERSION="0.13.9"\nKSCONF_BUILD="1315"\nKSCONF_VCS_INFO="Git SHA1 818f9187 committed on 2024-01-04"'

if __name__ == '__main__':
    print("# Please use 'python -m ksconf.version' instead.  This will eventually go away.")
    print(SHELL_VER_VARS)
