# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import beam_grpc_pb2 as beam__grpc__pb2
from .beam_grpc_pb2 import (pickled_response, info_response, set_variable_response,
                            get_variable_response, method_request, info_request, set_variable_request,
                            get_variable_request, func_request)

class BeamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.query_algorithm = channel.unary_unary(
                '/beam_grpc.BeamService/query_algorithm',
                request_serializer=method_request.SerializeToString,
                response_deserializer=pickled_response.FromString,
                )
        self.call_function = channel.unary_unary(
                '/beam_grpc.BeamService/call_function',
                request_serializer=func_request.SerializeToString,
                response_deserializer=pickled_response.FromString,
                )
        self.get_info = channel.unary_unary(
                '/beam_grpc.BeamService/get_info',
                request_serializer=info_request.SerializeToString,
                response_deserializer=info_response.FromString,
                )
        self.set_variable = channel.unary_unary(
                '/beam_grpc.BeamService/set_variable',
                request_serializer=set_variable_request.SerializeToString,
                response_deserializer=set_variable_response.FromString,
                )
        self.get_variable = channel.unary_unary(
                '/beam_grpc.BeamService/get_variable',
                request_serializer=get_variable_request.SerializeToString,
                response_deserializer=get_variable_response.FromString,
                )


class BeamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def query_algorithm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def call_function(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_variable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_variable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'query_algorithm': grpc.unary_unary_rpc_method_handler(
                    servicer.query_algorithm,
                    request_deserializer=method_request.FromString,
                    response_serializer=pickled_response.SerializeToString,
            ),
            'call_function': grpc.unary_unary_rpc_method_handler(
                    servicer.call_function,
                    request_deserializer=func_request.FromString,
                    response_serializer=pickled_response.SerializeToString,
            ),
            'get_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_info,
                    request_deserializer=info_request.FromString,
                    response_serializer=info_response.SerializeToString,
            ),
            'set_variable': grpc.unary_unary_rpc_method_handler(
                    servicer.set_variable,
                    request_deserializer=set_variable_request.FromString,
                    response_serializer=set_variable_response.SerializeToString,
            ),
            'get_variable': grpc.unary_unary_rpc_method_handler(
                    servicer.get_variable,
                    request_deserializer=get_variable_request.FromString,
                    response_serializer=get_variable_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beam_grpc.BeamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BeamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def query_algorithm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam_grpc.BeamService/query_algorithm',
            method_request.SerializeToString,
            pickled_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def call_function(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam_grpc.BeamService/call_function',
            func_request.SerializeToString,
            pickled_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam_grpc.BeamService/get_info',
            info_request.SerializeToString,
            info_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_variable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam_grpc.BeamService/set_variable',
            set_variable_request.SerializeToString,
            set_variable_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_variable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beam_grpc.BeamService/get_variable',
            get_variable_request.SerializeToString,
            get_variable_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
