# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beam_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62\x65\x61m_grpc.proto\x12\tbeam_grpc\",\n\x0c\x66unc_request\x12\x0c\n\x04\x61rgs\x18\x01 \x01(\x0c\x12\x0e\n\x06kwargs\x18\x02 \x01(\x0c\"C\n\x0emethod_request\x12\x13\n\x0bmethod_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\x0c\x12\x0e\n\x06kwargs\x18\x03 \x01(\x0c\"\"\n\x10pickled_response\x12\x0e\n\x06result\x18\x01 \x01(\x0c\"\x0e\n\x0cinfo_request\"\"\n\rinfo_response\x12\x11\n\tinfo_json\x18\x01 \x01(\t\"3\n\x14set_variable_request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"(\n\x15set_variable_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x14get_variable_request\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x15get_variable_response\x12\r\n\x05value\x18\x01 \x01(\x0c\x32\x8e\x03\n\x0b\x42\x65\x61mService\x12K\n\x0fquery_algorithm\x12\x19.beam_grpc.method_request\x1a\x1b.beam_grpc.pickled_response\"\x00\x12G\n\rcall_function\x12\x17.beam_grpc.func_request\x1a\x1b.beam_grpc.pickled_response\"\x00\x12?\n\x08get_info\x12\x17.beam_grpc.info_request\x1a\x18.beam_grpc.info_response\"\x00\x12S\n\x0cset_variable\x12\x1f.beam_grpc.set_variable_request\x1a .beam_grpc.set_variable_response\"\x00\x12S\n\x0cget_variable\x12\x1f.beam_grpc.get_variable_request\x1a .beam_grpc.get_variable_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'beam_grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FUNC_REQUEST']._serialized_start=30
  _globals['_FUNC_REQUEST']._serialized_end=74
  _globals['_METHOD_REQUEST']._serialized_start=76
  _globals['_METHOD_REQUEST']._serialized_end=143
  _globals['_PICKLED_RESPONSE']._serialized_start=145
  _globals['_PICKLED_RESPONSE']._serialized_end=179
  _globals['_INFO_REQUEST']._serialized_start=181
  _globals['_INFO_REQUEST']._serialized_end=195
  _globals['_INFO_RESPONSE']._serialized_start=197
  _globals['_INFO_RESPONSE']._serialized_end=231
  _globals['_SET_VARIABLE_REQUEST']._serialized_start=233
  _globals['_SET_VARIABLE_REQUEST']._serialized_end=284
  _globals['_SET_VARIABLE_RESPONSE']._serialized_start=286
  _globals['_SET_VARIABLE_RESPONSE']._serialized_end=326
  _globals['_GET_VARIABLE_REQUEST']._serialized_start=328
  _globals['_GET_VARIABLE_REQUEST']._serialized_end=364
  _globals['_GET_VARIABLE_RESPONSE']._serialized_start=366
  _globals['_GET_VARIABLE_RESPONSE']._serialized_end=404
  _globals['_BEAMSERVICE']._serialized_start=407
  _globals['_BEAMSERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
