
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-02T16:44:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "be064b2ecf8d45034b27a0dd699f4bda18c51ca4",
 "version": "2.27.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
