# Generated by Django 4.2.3 on 2024-01-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0013_abtest_content_abtest_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='expiration_day',
            field=models.IntegerField(default=None, help_text='유통기한 기간입니다. OrderFoodOrderLimit의 ', null=True),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='limit_type',
            field=models.IntegerField(choices=[(0, '미정'), (1, '재고형 limit'), (2, '로테이션형 limit')], default=1),
        ),
        migrations.AddField(
            model_name='foodproductorderlimit',
            name='manufactured_at',
            field=models.DateTimeField(default=None, help_text='생산날짜입니다', null=True),
        ),
        migrations.AddField(
            model_name='foodproductorderlimit',
            name='rotation_day',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='foodproductorderlimit',
            name='validated_at',
            field=models.DateTimeField(default=None, help_text='해당 상품의 유통기한입니다. 생산날짜와 FoodProduct의 expiration_day로 자동으로 기입됩니다.', null=True),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='sku',
            field=models.CharField(db_index=True, help_text='재고관리코드', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foodproductorderlimit',
            name='apply_at',
            field=models.DateTimeField(default=None, help_text='적용 시점', null=True),
        ),
        migrations.AlterField(
            model_name='foodproductorderlimit',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_limits', to='app_model.foodproduct'),
        ),
    ]
