
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-06T17:21:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9f12610cc02167703e042e3498f88728160af14",
 "version": "1.0.7-rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
