"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from . import request_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Chain(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class GlobalHeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    GLOBAL_HEADERS_FIELD_NUMBER: builtins.int
    GLOBAL_AUTH_FIELD_NUMBER: builtins.int
    REQUESTS_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    @property
    def global_headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def global_auth(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def requests(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[request_pb2.Request]: ...
    interval: builtins.int
    def __init__(
        self,
        *,
        global_headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        global_auth: collections.abc.Iterable[builtins.str] | None = ...,
        requests: collections.abc.Iterable[request_pb2.Request] | None = ...,
        interval: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["global_auth", b"global_auth", "global_headers", b"global_headers", "interval", b"interval", "requests", b"requests"]) -> None: ...

global___Chain = Chain
