
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-04T09:25:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb2d3e5dd79d85c2e3a6d39b735f9bae428ff71c",
 "version": "1.0.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
