
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T11:58:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d2dd0345056ca877a0487e4194ada6ad5de500a",
 "version": "5.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
