
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-03T13:45:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d0ab74452a608f0ae7f94e0eecd77c4536cd9ec",
 "version": "3.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
