
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T16:11:49+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae96e87bbbeb806762e247df1deb9f16035a4dea",
 "version": "0.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
