
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-05T16:29:59+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5813770d7c95d6d0ba451d1afed7ce9fddd5056",
 "version": "0.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
