KEY_ADDITIONAL_PROPERTIES_CONSOLIDATION_MODE = 'consolidationMode'
KEY_ADDITIONAL_PROPERTIES_DATA_PREVIEW = 'dataPreview'
KEY_ADDITIONAL_PROPERTIES_PII_DETECTION = 'isPIIDetectionEnabled'
KEY_ADDITIONAL_PROPERTIES_PII_DETECTION_LANGUAGE = 'language'
KEY_ADDITIONAL_PROPERTIES_READER_OPTIONS = 'readerOptions'
KEY_ADDITIONAL_PROPERTIES_ASSETS_ENCRYPTED = 'assetsEncrypted'
KEY_ADDITIONAL_PROPERTIES_ANOMALY_DETECTION = 'anomalyDetection'

ATTRIBUTE_NAME_IS_DELETED = 'SidraIsDeleted'
ATTRIBUTE_NAME_ASSET_ID = 'idsourceitem'
ATTRIBUTE_NAME_FILE_DATE = 'filedate'
ATTRIBUTE_NAME_HAS_ERRORS = 'HasErrors'
ATTRIBUTE_NAME_VIOLATED_CONSTRAINTS = 'ViolatedConstraints'
ATTRIBUTE_RAW_SUFFIX = "_SidraRaw";
ATTRIBUTE_PROCESSED_SUFFIX = "_SidraProc";

TABLE_VALIDATION_ERRORS_SUFFIX = "ValidationErrors";
TABLE_DELTA_SUFFIX = "Delta";
TABLE_LASTVERSION_VIEW_SUFFIX = "LastVersion";
TABLE_TEMP_JOIN_SUFFIX = "_tmpView";
TABLE_NAME_MAX_LEN = 128;
GUID_LEN_WITHOUT_HYPHENS = 32;
  
DATACATALOG_SAMPLE_NUMBER_RECORDS = 50
API_VERSION = '1.0'  
ID_DELTA_TABLE_FORMAT = 3
CONSOLIDATION_MODE_SNAPSHOT = 'Snapshot'
CONSOLIDATION_MODE_MERGE = 'Merge'
CONSOLIDATION_MODE_OVERWRITE = 'Overwrite'
CONSOLIDATION_MODE_UNKNOWN = 'Unknown'

# TODO: REVIEW Default values
DEFAULT_ID_TABLE_FORMAT = ID_DELTA_TABLE_FORMAT
DEFAULT_FILE_FORMAT = 'parquet'
DEFAULT_CONSOLIDATION_MODE = CONSOLIDATION_MODE_SNAPSHOT
DEFAULT_DATA_PREVIEW = True
DEFAULT_ANOMALY_DETECTION = True
DEFAULT_PII_DETECTION = False
DEFAULT_PII_DETECTION_LANGUAGE = 'en'
DEFAULT_GENERATE_DELTA_TABLE = False
DEFAULT_READER_OPTIONS = '{}'

IS_DELETED_COLUMN = 'SidraIsDeleted'

ANOMALY_DETECTION_DEFAULT_MAX_ASSET_HISTORY_LENGTH = 1000
ANOMALY_DETECTION_ASSET_STATUS = 2 # Finished
ANOMALY_DETECTION_MIN_ASSETS = 10