
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-04T10:36:11+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "2a289871cf91cfba9d4b3bbfb68ef3c408ca22a9",
 "version": "0.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
