
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-02T21:39:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f1b596e4ce40c2b29db622cb12031f3fc7ac881",
 "version": "0.1.4-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
