
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: random-first-package/random_first_package/random_first_package:dist

from setuptools import setup

setup(**{
    'author': 'Startup Unfiltered',
    'author_email': 'startup.unfiltered.2024@gmail.com',
    'description': 'Random First Package',
    'install_requires': (
        'pandas',
    ),
    'name': 'random_first_package',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        'random_first_package',
    ),
    'python_requires': '==3.9.*',
    'version': '0.1.1',
})
