
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-04T17:09:28-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9df5ba721c7ae216db092bb1dcf338a1cfdc0c98",
 "version": "2.14.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
