
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-03T10:04:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0129d17378575d11857429064979d537e0faee48",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
