
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-06T12:27:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdf1bfce876278a30a38e9ebf32ecf926a8c331b",
 "version": "1.109"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
