
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-03T19:35:12+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "49c715cc1886a6fae72666c5a4f85c807b2bd9a7",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
