"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SourceId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___SourceId = SourceId

@typing_extensions.final
class QueryId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___QueryId = QueryId

@typing_extensions.final
class QueryParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___QueryParameters = QueryParameters

@typing_extensions.final
class QueryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_ID_FIELD_NUMBER: builtins.int
    QUERY_ID_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    ASSOCIATED_MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    @property
    def source_id(self) -> global___SourceId: ...
    @property
    def query_id(self) -> global___QueryId: ...
    @property
    def parameters(self) -> global___QueryParameters: ...
    @property
    def associated_message_type(self) -> global___AssociatedMessageType: ...
    def __init__(
        self,
        *,
        source_id: global___SourceId | None = ...,
        query_id: global___QueryId | None = ...,
        parameters: global___QueryParameters | None = ...,
        associated_message_type: global___AssociatedMessageType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["associated_message_type", b"associated_message_type", "parameters", b"parameters", "query_id", b"query_id", "source_id", b"source_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["associated_message_type", b"associated_message_type", "parameters", b"parameters", "query_id", b"query_id", "source_id", b"source_id"]) -> None: ...

global___QueryRequest = QueryRequest

@typing_extensions.final
class QueryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class RowEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    ROW_FIELD_NUMBER: builtins.int
    @property
    def row(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        row: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["row", b"row"]) -> None: ...

global___QueryResponse = QueryResponse

@typing_extensions.final
class AssociatedMessageType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___AssociatedMessageType = AssociatedMessageType

@typing_extensions.final
class DbPullRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_ID_FIELD_NUMBER: builtins.int
    INIT_QUERY_ID_FIELD_NUMBER: builtins.int
    INIT_PARAMETERS_FIELD_NUMBER: builtins.int
    USE_COLUMNS_FIELD_NUMBER: builtins.int
    UPDATE_QUERY_ID_FIELD_NUMBER: builtins.int
    UPDATE_PARAMETERS_FIELD_NUMBER: builtins.int
    PULL_INTERVAL_FIELD_NUMBER: builtins.int
    ASSOCIATED_MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    @property
    def source_id(self) -> global___SourceId: ...
    @property
    def init_query_id(self) -> global___QueryId: ...
    @property
    def init_parameters(self) -> global___QueryParameters: ...
    @property
    def use_columns(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def update_query_id(self) -> global___QueryId: ...
    @property
    def update_parameters(self) -> global___QueryParameters: ...
    @property
    def pull_interval(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def associated_message_type(self) -> global___AssociatedMessageType: ...
    def __init__(
        self,
        *,
        source_id: global___SourceId | None = ...,
        init_query_id: global___QueryId | None = ...,
        init_parameters: global___QueryParameters | None = ...,
        use_columns: collections.abc.Iterable[builtins.str] | None = ...,
        update_query_id: global___QueryId | None = ...,
        update_parameters: global___QueryParameters | None = ...,
        pull_interval: google.protobuf.duration_pb2.Duration | None = ...,
        associated_message_type: global___AssociatedMessageType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["associated_message_type", b"associated_message_type", "init_parameters", b"init_parameters", "init_query_id", b"init_query_id", "pull_interval", b"pull_interval", "source_id", b"source_id", "update_parameters", b"update_parameters", "update_query_id", b"update_query_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["associated_message_type", b"associated_message_type", "init_parameters", b"init_parameters", "init_query_id", b"init_query_id", "pull_interval", b"pull_interval", "source_id", b"source_id", "update_parameters", b"update_parameters", "update_query_id", b"update_query_id", "use_columns", b"use_columns"]) -> None: ...

global___DbPullRequest = DbPullRequest

@typing_extensions.final
class PullTaskId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___PullTaskId = PullTaskId

@typing_extensions.final
class DbPullResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___PullTaskId: ...
    def __init__(
        self,
        *,
        id: global___PullTaskId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___DbPullResponse = DbPullResponse

@typing_extensions.final
class StopPullingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> global___PullTaskId: ...
    def __init__(
        self,
        *,
        id: global___PullTaskId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___StopPullingRequest = StopPullingRequest
