# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_iter.ipynb.

# %% auto 0
__all__ = ['itertype']

# %% ../nbs/01_iter.ipynb 6
#| export


# %% ../nbs/01_iter.ipynb 8
from typing import Iterable

# %% ../nbs/01_iter.ipynb 10
#| export


# %% ../nbs/01_iter.ipynb 12
from ptyp import Alias

# %% ../nbs/01_iter.ipynb 14
# from ltyp.strs import notstrbytes
# from ltyp.nums import num
# from ltyp.bool import bool01

# %% ../nbs/01_iter.ipynb 16
@Alias(Iterable)
class itertype: '''iterable type'''
