# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_nans.ipynb.

# %% auto 0
__all__ = ['none', 'nan', 'nanq', 'nans']

# %% ../nbs/04_nans.ipynb 6
#| export


# %% ../nbs/04_nans.ipynb 8
#| export


# %% ../nbs/04_nans.ipynb 10
#| export


# %% ../nbs/04_nans.ipynb 12
from ptyp import Alias, Not, Opt
from itry import npnan, npNaN, npNAN, pdna, ptnan, nan as pynan, nonetype, number, nparray

# %% ../nbs/04_nans.ipynb 14
from .iter import itertype
from .bool import bools
from .nums import nums

# %% ../nbs/04_nans.ipynb 17
@Alias(None, nonetype)
class none: '''None or NoneType'''

# %% ../nbs/04_nans.ipynb 20
@Alias(pynan, pdna, npnan, npNaN, npNAN, ptnan)
class nan: '''math.nan, pd.NA, np.nan, np.NaN, or np.NAN'''

@Opt(nan)
class nanq: '''math.nan, pd.NA, np.nan, np.NaN, np.NAN, or None'''

@Alias(nan, list, tuple, itertype, nparray, attrs=dict(dtype=nan))
class nans: '''list of nan'''
