# Generated by Django 4.2.1 on 2023-05-10 19:46

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtail_sb_admin_interface", "0006_theme_sidebar_logo_background_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_critical",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#cd4444",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="Critical color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_info",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#1f7e9a",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="Informative color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_positive",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#1b8666",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="Positive color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_primary",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#2e1f5e",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="Primary color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_secondary",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#007d7e",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="Secondary color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="color_warning",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#faa500",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="Warning color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(
                default="Wagtail", max_length=50, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sidebar_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sidebar_logo_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#ffffff",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="Background color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sidebar_logo_collapsed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo (collapsed)",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sidebar_logo_shape",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Original"),
                    ("circular", "Circular"),
                    ("rectangular", "Rectangular"),
                    ("square", "Square"),
                ],
                default="",
                max_length=50,
                verbose_name="Shape of logo",
            ),
        ),
    ]
