
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-05T23:45:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9152ff6551186bb77ceb8cbac51abf1c9b75c232",
 "version": "1.66.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
