# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_bool.ipynb.

# %% auto 0
__all__ = ['bool01', 'bools', 'iterbool']

# %% ../nbs/02_bool.ipynb 6
#| export


# %% ../nbs/02_bool.ipynb 8
from typing import TypeAlias

# %% ../nbs/02_bool.ipynb 10
#| export


# %% ../nbs/02_bool.ipynb 12
from ptyp import Alias
from itry import npbool

# %% ../nbs/02_bool.ipynb 14
from .iter import itertype

# %% ../nbs/02_bool.ipynb 16
@Alias(bool, npbool, 0, 1)
class bool01: '''bool, np.bool_, 0, 1'''

# %% ../nbs/02_bool.ipynb 17
@Alias(list, tuple, itertype, attrs=dict(dtype=bool01))
class bools: '''list of bool01'''

@Alias(itertype, attrs=dict(dtype=bool01))
class iterbool: '''iterable of `bool`'''
