# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_strs.ipynb.

# %% auto 0
__all__ = ['strq', 'nilstr', 'pttn', 'strtmpl', 'strbytes', 'notnilstr', 'notstrbytes', 'strs', 'iterstr']

# %% ../nbs/05_strs.ipynb 6
#| export


# %% ../nbs/05_strs.ipynb 8
from typing import Literal

# %% ../nbs/05_strs.ipynb 10
#| export


# %% ../nbs/05_strs.ipynb 12
from ptyp import Alias, Opt, Not
from itry import repattern, strtemplate

# %% ../nbs/05_strs.ipynb 14
from .iter import itertype

# %% ../nbs/05_strs.ipynb 16
@Opt(str)
class strq: '''str or None'''

# %% ../nbs/05_strs.ipynb 17
@Alias(Literal[''])
class nilstr: ...

@Alias(repattern)
class pttn: ...

@Alias(str, strtemplate)
class strtmpl: ...

@Alias(str, bytes)
class strbytes: ...

# %% ../nbs/05_strs.ipynb 18
@Not(nilstr)
class notnilstr: ...

@Not(str, bytes)
class notstrbytes: ...

# %% ../nbs/05_strs.ipynb 19
@Alias(list, tuple, itertype, notstrbytes, attrs=dict(dtype=str))
class strs: '''iterable of `str`'''

@Alias(itertype, notstrbytes, attrs=dict(dtype=str))
class iterstr: '''iterable of `str`'''
