
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-02T17:57:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "51a287cf50b2a217c433e489408c6602e9291dde",
 "version": "2.27.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
