

def Ylm(l: int, m: int, theta: float, phi: float) -> complex: ...

def m_times_Ylm_over_sin_theta(l: int, m: int, theta: float, phi: float) -> complex: ...

def dYlm_dtheta(l: int, m: int, theta: float, phi: float) -> complex: ...