
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-04T12:52:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "23520f65adf7df40165083b59fca4e61bde22ac6",
 "version": "2.27.0rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
