# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrequest.proto\"\xd9\x01\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12)\n\tjson_data\x18\x03 \x03(\x0b\x32\x16.Request.JsonDataEntry\x12\x13\n\x0b\x63\x61pture_key\x18\x04 \x01(\t\x12\x1f\n\x17wait_for_response_field\x18\x05 \x01(\t\x12\x1f\n\x17wait_for_response_value\x18\x06 \x01(\t\x1a/\n\rJsonDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST_JSONDATAENTRY._options = None
  _REQUEST_JSONDATAENTRY._serialized_options = b'8\001'
  _REQUEST._serialized_start=18
  _REQUEST._serialized_end=235
  _REQUEST_JSONDATAENTRY._serialized_start=188
  _REQUEST_JSONDATAENTRY._serialized_end=235
# @@protoc_insertion_point(module_scope)
