
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: dependatool:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"Pip dependabot checker used in Envoy proxy\'s CI"',
    'entry_points': {
        'console_scripts': [
            'dependatool=dependatool:cmd',
        ],
    },
    'install_requires': (
        'abstracts>=0.0.12',
        'aio.core>=0.10.1',
        'aio.run.checker>=0.5.7',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
dependatool
==========================

Pip dependabot checker used in Envoy proxy's CI
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'dependatool',
    'namespace_packages': (
    ),
    'package_data': {
        'dependatool': (
            'py.typed',
        ),
    },
    'packages': (
        'dependatool',
        'dependatool.abstract',
        'dependatool.docker',
        'dependatool.gomod',
        'dependatool.npm',
        'dependatool.pip',
    ),
    'python_requires': '>=3.10.0',
    'url': 'https://github.com/envoyproxy/toolshed/tree/main/dependatool',
    'version': '0.2.3',
})
