
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-03T09:19:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "07a277278f3bdce883687dcf653c4395c2219831",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
