
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-06T17:30:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "75bade51c7064f4a350a7c7be5d61f629acc4bc1",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
