
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-05T11:23:28-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "176f53075ec7245dac492637442a370ca544534f",
 "version": "2024.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
