
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-03T21:22:07+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "2f6bc814c683d1a073ab6c77793f717735e55665",
 "version": "0.6.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
