
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T10:36:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "25606bf8618787cc53f21f848614996dd63b3b64",
 "version": "5.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
