# Generated by Django 3.2.18 on 2023-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hashtag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mytag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
