# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.05.232702'

RELEASE_GIT_HEAD = 'b6951271ac014761c9c317b9cecd5e8e139cfa7c'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.01.05.232702dev'
