
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-28T19:51:20-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "5c2afc3f9b29cf40a884012d938b1bcfb7af467a",
 "version": "0+untagged.59.g5c2afc3.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
