VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('04')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('53')
MAJOR_VERSION = 1
MINOR_VERSION = 10
PATCH_VERSION = 202401041253
version_date = '2024/01/04 12:53'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
