# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/itry',
                'doc_host': 'https://dsm-72.github.io',
                'git_url': 'https://github.com/dsm-72/itry',
                'lib_path': 'itry'},
  'syms': { 'itry.atyp': {},
            'itry.core': { 'itry.core._getsig': ('core.html#_getsig', 'itry/core.py'),
                           'itry.core._setsig': ('core.html#_setsig', 'itry/core.py'),
                           'itry.core.imod': ('core.html#imod', 'itry/core.py'),
                           'itry.core.itry': ('core.html#itry', 'itry/core.py'),
                           'itry.core.tnew': ('core.html#tnew', 'itry/core.py')},
            'itry.trys': {}}}
