
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T11:45:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1dbef1b51c23f22e9d8b50235ae43cc9356e98e3",
 "version": "5.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
